import { Router } from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_FILE = path.join(__dirname, '..', 'data', 'backlinks.json');

async function readAll() {
  try {
    const raw = await fs.readFile(DATA_FILE, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

async function writeAll(items) {
  await fs.mkdir(path.dirname(DATA_FILE), { recursive: true });
  await fs.writeFile(DATA_FILE, JSON.stringify(items, null, 2));
}

const router = Router();

// GET /api/backlinks
router.get('/', async (req, res) => {
  res.json(await readAll());
});

// POST /api/backlinks  { sourceUrl, targetUrl, anchorText, status, quality, notes }
router.post('/', async (req, res) => {
  const items = await readAll();
  const entry = {
    id: Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
    sourceUrl: req.body.sourceUrl || '',
    targetUrl: req.body.targetUrl || '',
    anchorText: req.body.anchorText || '',
    status: req.body.status || 'pending', // pending | live | lost | disavowed
    quality: req.body.quality || 'unrated', // good | spam | unrated
    notes: req.body.notes || '',
    addedAt: new Date().toISOString(),
  };
  items.push(entry);
  await writeAll(items);
  res.status(201).json(entry);
});

// PATCH /api/backlinks/:id
router.patch('/:id', async (req, res) => {
  const items = await readAll();
  const idx = items.findIndex((i) => i.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: 'Not found' });
  items[idx] = { ...items[idx], ...req.body, id: items[idx].id };
  await writeAll(items);
  res.json(items[idx]);
});

// DELETE /api/backlinks/:id
router.delete('/:id', async (req, res) => {
  const items = await readAll();
  const next = items.filter((i) => i.id !== req.params.id);
  await writeAll(next);
  res.json({ ok: true });
});

// GET /api/backlinks/export/csv
router.get('/export/csv', async (req, res) => {
  const items = await readAll();
  const header = 'sourceUrl,targetUrl,anchorText,status,quality,notes,addedAt\n';
  const rows = items
    .map((i) =>
      [i.sourceUrl, i.targetUrl, i.anchorText, i.status, i.quality, i.notes, i.addedAt]
        .map((v) => `"${String(v).replace(/"/g, '""')}"`)
        .join(',')
    )
    .join('\n');
  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', 'attachment; filename="backlinks.csv"');
  res.send(header + rows);
});

// GET /api/backlinks/export/disavow
// Google disavow tool expects one domain/url per line, "domain:" prefix for whole-domain disavows.
router.get('/export/disavow', async (req, res) => {
  const items = await readAll();
  const spammy = items.filter((i) => i.quality === 'spam');
  const lines = spammy.map((i) => {
    try {
      const host = new URL(i.sourceUrl).hostname;
      return `domain:${host}`;
    } catch {
      return i.sourceUrl;
    }
  });
  const unique = Array.from(new Set(lines));
  const content = `# Disavow file generated by Backlink Tool on ${new Date().toISOString()}\n` + unique.join('\n') + '\n';
  res.setHeader('Content-Type', 'text/plain');
  res.setHeader('Content-Disposition', 'attachment; filename="disavow.txt"');
  res.send(content);
});

export default router;
